extends: airbnb-base
env:
  browser: true
  node: true
  mocha: true
rules:
  no-console: off
  semi:
    - error
    - never
  no-use-before-define:
    - error
    - functions: false
      classes: true
  no-underscore-dangle: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
