extends: airbnb-base
env:
  browser: true
  node: true
  mocha: true
rules:
  no-console: off
  semi:
    - error
    - never
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
