language: node_js
node_js:
  - "6"
services: mysql
env:
  global:
    - MYSQL_HOSTNAME=localhost
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=benar

before_install:
  - npm install -g elm

before_script:
  - npm run build-client
