language: node_js
node_js:
  - "6"
services: mysql
env:
  global:
    - NODE_ENV=test
    - MYSQL_HOSTNAME=localhost
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=benar

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

cache:
  directories:
    - elm-stuff/build-artifacts

before_install:
  - npm install -g elm

before_script:
  - cp .env.default .env
  - npm run build-client
  - npm run createDb

after_script:
  - npm run destroyDb
