version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
