-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 18:56:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema benar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `portal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `site_url` VARCHAR(255) NOT NULL,
  `logo_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `name_slug` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NULL,
  `avatar_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_slug_UNIQUE` (`name_slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `portal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_article_portal_idx` (`portal_id` ASC),
  INDEX `fk_article_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_article_portal`
    FOREIGN KEY (`portal_id`)
    REFERENCES `portal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `article_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_review_article1_idx` (`article_id` ASC),
  INDEX `fk_review_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_review_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vote_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vote_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flag_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flag_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `review_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `parent_feedback_id` INT UNSIGNED NULL,
  `content` TEXT NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_feedback_review1_idx` (`review_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_feedback1_idx` (`parent_feedback_id` ASC),
  INDEX `fk_feedback_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_feedback_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_feedback1`
    FOREIGN KEY (`parent_feedback_id`)
    REFERENCES `feedback` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_topic` (
  `article_id` INT UNSIGNED NOT NULL,
  `topic_id` INT UNSIGNED NOT NULL,
  INDEX `fk_article_topic_article1_idx` (`article_id` ASC),
  INDEX `fk_article_topic_topic1_idx` (`topic_id` ASC),
  CONSTRAINT `fk_article_topic_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_topic_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_vote` (
  `article_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `vote_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_article_vote_article1_idx` (`article_id` ASC),
  INDEX `fk_article_vote_member1_idx` (`member_id` ASC),
  INDEX `fk_article_vote_vote_type1_idx` (`vote_type_id` ASC),
  UNIQUE INDEX `article_vote_UNIQUE` (`article_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_article_vote_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_vote_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_vote_vote_type1`
    FOREIGN KEY (`vote_type_id`)
    REFERENCES `vote_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article_flag` (
  `article_id` INT UNSIGNED NOT NULL,
  `flag_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_article_flag_article1_idx` (`article_id` ASC),
  INDEX `fk_article_flag_flag_type1_idx` (`flag_type_id` ASC),
  CONSTRAINT `fk_article_flag_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_flag_flag_type1`
    FOREIGN KEY (`flag_type_id`)
    REFERENCES `flag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_vote` (
  `review_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `vote_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_review_vote_review1_idx` (`review_id` ASC),
  INDEX `fk_review_vote_member1_idx` (`member_id` ASC),
  INDEX `fk_review_vote_vote_type1_idx` (`vote_type_id` ASC),
  UNIQUE INDEX `review_vote_UNIQUE` (`review_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_review_vote_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_vote_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_vote_vote_type1`
    FOREIGN KEY (`vote_type_id`)
    REFERENCES `vote_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review_flag` (
  `review_id` INT UNSIGNED NOT NULL,
  `flag_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_review_flag_review1_idx` (`review_id` ASC),
  INDEX `fk_review_flag_flag_type1_idx` (`flag_type_id` ASC),
  CONSTRAINT `fk_review_flag_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_flag_flag_type1`
    FOREIGN KEY (`flag_type_id`)
    REFERENCES `flag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member_flag` (
  `member_id` INT UNSIGNED NOT NULL,
  `flag_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_member_flag_member1_idx` (`member_id` ASC),
  INDEX `fk_member_flag_flag_type1_idx` (`flag_type_id` ASC),
  CONSTRAINT `fk_member_flag_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_flag_flag_type1`
    FOREIGN KEY (`flag_type_id`)
    REFERENCES `flag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member_role` (
  `member_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  INDEX `fk_member_role_member1_idx` (`member_id` ASC),
  INDEX `fk_member_role_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_member_role_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback_vote` (
  `feedback_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  `vote_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_feedback_vote_feedback1_idx` (`feedback_id` ASC),
  INDEX `fk_feedback_vote_member1_idx` (`member_id` ASC),
  INDEX `fk_feedback_vote_vote_type1_idx` (`vote_type_id` ASC),
  UNIQUE INDEX `feedback_vote_UNIQUE` (`feedback_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_feedback_vote_feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `feedback` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_vote_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_vote_vote_type1`
    FOREIGN KEY (`vote_type_id`)
    REFERENCES `vote_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_flag` (
  `portal_id` INT UNSIGNED NOT NULL,
  `flag_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_portal_flag_portal1_idx` (`portal_id` ASC),
  INDEX `fk_portal_flag_flag_type1_idx` (`flag_type_id` ASC),
  CONSTRAINT `fk_portal_flag_portal1`
    FOREIGN KEY (`portal_id`)
    REFERENCES `portal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portal_flag_flag_type1`
    FOREIGN KEY (`flag_type_id`)
    REFERENCES `flag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback_flag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback_flag` (
  `feedback_id` INT UNSIGNED NOT NULL,
  `flag_type_id` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_feedback_flag_feedback1_idx` (`feedback_id` ASC),
  INDEX `fk_feedback_flag_flag_type1_idx` (`flag_type_id` ASC),
  CONSTRAINT `fk_feedback_flag_feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `feedback` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_flag_flag_type1`
    FOREIGN KEY (`flag_type_id`)
    REFERENCES `flag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `vote_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `vote_type` (`id`, `name`) VALUES (1, 'Upvote');
INSERT INTO `vote_type` (`id`, `name`) VALUES (2, 'Downvote');
INSERT INTO `vote_type` (`id`, `name`) VALUES (3, 'Review Needed');
INSERT INTO `vote_type` (`id`, `name`) VALUES (4, 'Inappropriate');

COMMIT;


-- -----------------------------------------------------
-- Data for table `flag_type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `flag_type` (`id`, `name`) VALUES (1, 'Deleted');
INSERT INTO `flag_type` (`id`, `name`) VALUES (2, 'Need Improvement');
INSERT INTO `flag_type` (`id`, `name`) VALUES (3, 'Collapsed');
INSERT INTO `flag_type` (`id`, `name`) VALUES (4, 'Banned');

COMMIT;


-- -----------------------------------------------------
-- Data for table `role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `role` (`id`, `name`) VALUES (1, 'Member');
INSERT INTO `role` (`id`, `name`) VALUES (2, 'Administrator');
INSERT INTO `role` (`id`, `name`) VALUES (3, 'Moderator');

COMMIT;

